# Generated by Django 2.1.4 on 2019-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='tags',
            field=models.ManyToManyField(to='suggester.Tags'),
        ),
    ]
