# Generated by Django 2.1.5 on 2019-02-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggester', '0002_auto_20190203_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='tags',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='cuisine_type',
            field=models.TextField(choices=[('TH', 'Thai'), ('CN', 'Chinese'), ('ID', 'Indonesian'), ('JP', 'Japanese'), ('MY', 'Malay'), ('IN', 'Indian'), ('WS', 'Western'), ('DS', 'Dessert'), ('BR', 'Brunch'), ('FF', 'Fast Food'), ('NT', 'No Type')], default='NT'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
