# Generated by Django 2.1.5 on 2019-02-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggester', '0003_addcuisinetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='cuisine_type',
            field=models.TextField(choices=[('TH', 'Thai'), ('CN', 'Chinese'), ('ID', 'Indonesian'), ('JP', 'Japanese'), ('MY', 'Malay'), ('IN', 'Indian'), ('WS', 'Western'), ('DS', 'Dessert'), ('BR', 'Brunch'), ('FF', 'Fast Food'), ('KR', 'Korean'), ('NT', 'No Type')], default='NT'),
        ),
    ]
